# Generated by Django 3.2.6 on 2021-08-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210830_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pfp',
            field=models.ImageField(default=1, upload_to='static/img/{user.username}'),
            preserve_default=False,
        ),
    ]
