# Generated by Django 3.2.6 on 2021-08-31 10:09

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_userinfo_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='location',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.path_and_rename),
        ),
    ]
