# Generated by Django 3.2.6 on 2021-09-01 06:58

from django.db import migrations, models
import home.models
import home.storage


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210831_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pfp',
            field=models.ImageField(blank=True, null=True, storage=home.storage.OverwriteStorage(), upload_to=home.models.path_and_rename),
        ),
    ]
