# Generated by Django 3.2.6 on 2021-08-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='post',
            new_name='blog',
        ),
    ]
